### ISSUE TITLE
Expédition récentes "mots anglais"

### ISSUE THREAD

**Issue by Mounia-kazi** [achraf13/TRACK-IN#17]
Changer "search" et mettre "recherche" ainsi que "showing 1 to 5 of 5 entries" et le traduire en français.

**Comment by aminekehlimoussab** [comment]
c'est fait, tout les mots ont été traduit

**Comment by Mounia-kazi** [comment]
Très bien. Mette un espace entre les : et le mot "Rechercher".

**Comment by aminekehlimoussab** [comment]
c'est fait
