### ISSUE TITLE
Adresse (nombre aléatoire)

### ISSUE THREAD

**Issue by salimKazi** [achraf13/TRACK-IN#26]
Génération d'un code ou nombre sans l'écrire dans l'étiquette que ce soit pour le coté expéditeur ou destinataire

**Comment by aminekehlimoussab** [comment]
le code généré c'est le code de la commune de l'adresse, j'ai remplacé le le code par le nom de la commune

**Comment by salimKazi** [comment]
Oui, c'est mieux
