### ISSUE TITLE
Détail destinataire 

### ISSUE THREAD

**Issue by salimKazi** [achraf13/TRACK-IN#34]
Aucune information ne s'affiche lorsqu'on clique sur l'icone qui nous affiche les info du destinataire

**Comment by aminekehlimoussab** [comment]
oui effectivement, le problème vient de la base de donnée, parce que hier j'ai supprimé la base de donnée des adresses, et comme se sont des expéditions qui ont été faite avec l'ancienne base de donnée les informations de destinataire n'existe plus dans la base de donnée, donc sa n'affiche rien.

**Comment by aminekehlimoussab** [comment]
j'ai supprimé les expéditions qui ont causé le problème
