### ISSUE TITLE
Profil client

### ISSUE THREAD

**Issue by salimKazi** [achraf13/TRACK-IN#37]
le premier chiffre du numéro de téléphone portable disparaît  non pas lors de l'enregistrement du client mais après quand on veut modifier son profil.
Un zéro s'affiche aussi pour ce qui est du téléphone fixe et le fax.

**Comment by aminekehlimoussab** [comment]
c'est corrigé

**Comment by salimKazi** [comment]
Oui, pour le numéro de portable, maintenant ça génère deux  "0" pour le numéro de fixe et le fax

**Comment by aminekehlimoussab** [comment]
c'est corrigé
